export const KUTYALISTA = [
    {
        kephely: "./images/kutya0.jpg",
        nev: "Gizmo",
        kor: 12,
        fajta: "foxterrier",
        lab: 4,
        nem: "kan",
        marmagassag: 35,
        
    },
    {   kephely: "./images/kutya1.jpg",
        nev: "Bogyó",
        kor: 8,
        fajta: "kuvasz",
        lab: 4,
        nem: "szuka",
        marmagassag: 70,
        
    },
    {   kephely: "./images/kutya2.jpg",
        nev: "Sörény",
        kor: 14,
        fajta: "puli",
        lab: 4,
        nem: "kan",
        marmagassag: 40,
        
    },
    {   kephely: "./images/kutya3.jpg",
        nev: "Kifli",
        kor: 11,
        fajta: "agár",
        lab: 4,
        nem: "kan",
        marmagassag: 65,
        
    },
    {   kephely: "./images/kutya4.jpg",
        nev: "Mogyoró",
        kor: 12,
        fajta: "újfundlandi",
        lab: 4,
        nem: "kan",
        marmagassag: 70,
        
    },
    {   kephely: "./images/kutya5.jpg",
        nev: "Sajó",
        kor: 9,
        fajta: "keverék",
        lab: 4,
        nem: "szuka",
        marmagassag: 50,
        
    },
    {   kephely: "./images/kutya6.jpg",
        nev: "Tücsök",
        kor: 4,
        fajta:"agár",
        lab:4,
        nem: "kan",
        marmagassag: 40,
        
    },
    {   kephely: "./images/kutya7.jpg",
        nev: "Répa",
        kor: 6,
        fajta:"agár",
        lab:4,
        nem: "szuka",
        marmagassag: 38,
        
    },
    {
        kephely: "./images/kutya0.jpg",
        nev: "Gizmo",
        kor: 12,
        fajta: "foxterrier",
        lab: 4,
        nem: "kan",
        marmagassag: 35,
        
    },
    {   kephely: "./images/kutya1.jpg",
        nev: "Bogyó",
        kor: 8,
        fajta: "kuvasz",
        lab: 4,
        nem: "szuka",
        marmagassag: 70,
        
    },
    {   kephely: "./images/kutya2.jpg",
        nev: "Sörény",
        kor: 14,
        fajta: "puli",
        lab: 4,
        nem: "kan",
        marmagassag: 40,
        
    },
    {   kephely: "./images/kutya3.jpg",
        nev: "Kifli",
        kor: 11,
        fajta: "agár",
        lab: 4,
        nem: "kan",
        marmagassag: 65,
        
    },
    {   kephely: "./images/kutya4.jpg",
        nev: "Mogyoró",
        kor: 12,
        fajta: "újfundlandi",
        lab: 4,
        nem: "kan",
        marmagassag: 70,
        
    },
    {   kephely: "./images/kutya5.jpg",
        nev: "Sajó",
        kor: 9,
        fajta: "keverék",
        lab: 4,
        nem: "szuka",
        marmagassag: 50,
        
    },
    {   kephely: "./images/kutya6.jpg",
        nev: "Tücsök",
        kor: 4,
        fajta:"agár",
        lab:4,
        nem: "kan",
        marmagassag: 40,
        
    },
    {   kephely: "./images/kutya7.jpg",
        nev: "Répa",
        kor: 6,
        fajta:"agár",
        lab:4,
        nem: "szuka",
        marmagassag: 38,
        
    }
];

export const KUTYAKULCS = {
    kephely: "képhely",
    nev: "név",
    kor: "kor",
    fajta: "fajta",
    lab: "láb",
    nem: "ivar",
    marmagassag: "marmagasság",
    

}